package:
  name: pypandoc
  version: "1.1.3"

source:
  fn: pypandoc-1.1.3.zip
  url: https://files.pythonhosted.org/packages/41/68/e985491370cc44a063ac5c70232bf72d7675fa7539a86fa7fa08257bda05/pypandoc-1.1.3.zip
  md5: 771f376bf9c936a90159cd94235998c2
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pypandoc = pypandoc:main
    #
    # Would create an entry point called pypandoc that calls pypandoc.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  # Python imports
  imports:
    - pypandoc

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/bebraw/pypandoc
  license: MIT License
  summary: 'Thin wrapper for pandoc.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
