package:
  name: flatdict
  version: "1.2.0"

source:
  fn: flatdict-1.2.0.tar.gz
  url: https://pypi.python.org/packages/6c/ed/a17e9d48bf3ab8e0aff10c653093c56cfc7b711c67b9836deea101b29508/flatdict-1.2.0.tar.gz
  md5: 91d2f7a6851b399986f3b6929eac1716
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - flatdict = flatdict:main
    #
    # Would create an entry point called flatdict that calls flatdict.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/gmr/flatdict
  license: BSD License
  summary: 'Python module for interacting with nested dicts as a single level dict with delimited keys.'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
