package:
  name: hyperas
  version: "0.3.dev"

source:
  git_url: https://github.com/maxpumperla/hyperas.git
  #fn: hyperas-0.2.tar.gz
  #url: https://files.pythonhosted.org/packages/75/24/181e010fdb1c0a7b3cb5288b5a32b414e9d087c3a5331988df59ab3dd624/hyperas-0.2.tar.gz
  #md5: 4f91f4c57743f3af1e6fe9dc45d4d4e3
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - hyperas = hyperas:main
    #
    # Would create an entry point called hyperas that calls hyperas.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - keras
    - hyperopt

  run:
    - python
    - keras
    - hyperopt

test:
  # Python imports
  imports:
    - hyperas

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/maxpumperla/hyperas
  license: MIT
  summary: 'Simple wrapper for hyperopt to do convenient hyperparameter optimization for Keras models'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
