package:
  name: h5py
  version: "2.6.0"

source:
  fn: h5py-2.6.0.tar.gz
  url: https://pypi.python.org/packages/22/82/64dada5382a60471f85f16eb7d01cc1a9620aea855cd665609adf6fdbb0d/h5py-2.6.0.tar.gz
  md5: ec476211bd1de3f5ac150544189b0bf4
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - h5py = h5py:main
    #
    # Would create an entry point called h5py that calls h5py.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.6.1
    - six

  run:
    - python
    - numpy >=1.6.1
    - six

test:
  # Python imports
  imports:
    - h5py
    - h5py._hl
    - h5py.tests
    - h5py.tests.hl
    - h5py.tests.old

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.h5py.org
  license: BSD License
  summary: 'Read and write HDF5 files from Python'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
