package:
  name: hyperopt
  version: 0.1.2

source:
    git_url: https://github.com/hyperopt/hyperopt.git

    #fn: hyperopt-0.1.tar.gz
    #url: https://pypi.python.org/packages/39/51/16e9edb51ffbf64bd80f41b7d30bc037aa8b157d430c276464c9b8768b67/hyperopt-0.1.tar.gz
    #md5: f5e4e94f2942a4f8661329dd6fdc31a5

#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - theano = theano:main
    #
    # Would create an entry point called theano that calls theano.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - numpy
    - scipy
    - nose
    - pymongo
    - six
    - networkx
    - future
    - tqdm

  run:
    - python
    - numpy
    - scipy
    - nose
    - pymongo
    - six
    - networkx
    - future
    - tqdm

test:
  requires:
    - nose
  # Python imports
  imports:
    - hyperopt
    - hyperopt.hp
    - hyperopt.tpe
    - hyperopt.fmin

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/hyperopt/hyperopt
  license: BSD License
  summary: 'Distributed Asynchronous Hyper-parameter Optimization'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
