package:
  name: hyperopt
  version: !!str 0.0.3.dev1

source:
  git_url: https://github.com/hyperopt/hyperopt.git
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - theano = theano:main
    #
    # Would create an entry point called theano that calls theano.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - numpy
    - scipy
    - nose
    - pymongo
    - networkx

  run:
    - numpy
    - scipy
    - nose
    - pymongo
    - networkx

test:
  requires:
    - nose
  # Python imports
  imports:
    - hyperopt

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/hyperopt/hyperopt
  license: BSD License
  summary: 'Distributed Asynchronous Hyper-parameter Optimization'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
