package:
  name: tqdm
  version: "4.7.6"

source:
  fn: tqdm-4.7.6.tar.gz
  url: https://files.pythonhosted.org/packages/ac/69/230201e59820455e4b3470c04c0153bb492bf7e885681c5c46635d273815/tqdm-4.7.6.tar.gz
  md5: eec84bc7ecbaa47a5d1327bfa32fcbd2
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - tqdm = tqdm:main
    #
    # Would create an entry point called tqdm that calls tqdm.main()

    - tqdm=tqdm._main:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - tqdm

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - tqdm --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - coverage
    - flake8
    - nose
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/tqdm/tqdm
  license: Mozilla Public License 2.0 (MPL 2.0) or MIT License
  summary: 'A Fast, Extensible Progress Meter'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
