package:
  name: keras
  version: "1.2.0"

source:
  fn: Keras-1.2.0.tar.gz
  url: https://pypi.python.org/packages/ef/39/06886076de3d1eaae6df9aace977284a3c1267f8576c3d07ca0d37437b38/Keras-1.2.0.tar.gz
  md5: d24d8b72747f8cc38e659ce8fc92ad3c
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - keras = keras:main
    #
    # Would create an entry point called keras that calls keras.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - theano
    - pyyaml
    - six

  run:
    - python
    - theano
    - pyyaml
    - six
    - h5py

test:
  # Python imports
  imports:
    - keras
    - keras.backend
    - keras.datasets
    - keras.engine
    - keras.layers
    - keras.preprocessing
    - keras.utils
    - keras.wrappers

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/fchollet/keras
  license: MIT
  summary: 'Deep Learning for Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
