package:
  name: keras
  version: "1.0.4"

source:
  fn: Keras-1.0.4.tar.gz
  url: https://pypi.python.org/packages/f5/af/282be3761ccf419a8f5fdb99407724c108beee2871c13c1f3b01d3a203e3/Keras-1.0.4.tar.gz
  md5: 5c0a39e9ea48b94aa2ffd398f33ed643
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - keras = keras:main
    #
    # Would create an entry point called keras that calls keras.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - theano
    - pyyaml
    - six

  run:
    - python
    - theano
    - pyyaml
    - six

test:
  # Python imports
  imports:
    - keras
    - keras.backend
    - keras.datasets
    - keras.engine
    - keras.layers
    - keras.legacy
    - keras.preprocessing
    - keras.utils
    - keras.wrappers

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/fchollet/keras
  license: MIT
  summary: 'Deep Learning for Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
